name: dotnet build and test

on:
  - push
  - pull_request

# See: https://docs.microsoft.com/ja-jp/dotnet/devops/dotnet-test-github-action
#      https://docs.microsoft.com/ja-jp/aspnet/core/host-and-deploy/visual-studio-publish-profiles?view=aspnetcore-5.0#folder-publish-example
jobs:
  on-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test
  on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Build
        run: dotnet build --configuration DebugExcludeWPF
      - name: Test
        run: dotnet test --configuration DebugExcludeWPF

